version: '3.8'

services:
  discord_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord_bot
    command: ["./discord_bot"]
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
      GUILD_ID: ${GUILD_ID}